import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';

import { dark } from "@clerk/themes";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

const plexMONO = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400","500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      theme: dark,
    }
      
    }>

      

      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.variable} ${plexMONO.variable} antialiased`}
        >

          <ThemeProvider  attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange>
              
             <header>
              <SignedOut>
                <SignInButton />
                
                <button className="bg-rose-500 text-white p-2 rounded">Sign Up</button>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
             </header>
              {children}
          </ThemeProvider>
         
        </body>
      </html>
    </ClerkProvider>
  );
}

